version: 0.2

env:
  parameter-store:
    DIGIGALLERY_BUILD_BUCKET_NAME: DIGIGALLERY_BUILD_BUCKET
phases:
  install:
    runtime-versions:
        nodejs: 12
  build:
    commands:
      - rm -f package-lock.json
      - export BUCKET=$DIGIGALLERY_BUILD_BUCKET_NAME
      - npm run build
      - aws cloudformation package --template-file template.yaml --output-template-file outputtemplate.yaml --s3-bucket $BUCKET --s3-prefix digigallery-metadata
artifacts:
  type: zip
  files:
    - '**/*'
  name: code